---
title: Book Summaries
author: Mauro Camara Escudero
date: '2020-12-28'
slug: books
categories:
tags:
subtitle: 'A curated list of summaries and insights from Books I enjoyed.'
summary: 'A curated list of summaries and insights from Books I enjoyed.'
authors: []
lastmod: '2020-12-28T14:14:07+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

- <span style="color:darkred">**History and Politics**</span>
  - [The Shortest History of England](#history-england)
- <span style="color:goldenrod">**Nutrition**</span>
- <span style="color:blueviolet">**Mental Health**</span>
  - [The Man Who Couldn't Stop](#ocd)


# <span style="color:darkred"> History </span>

<div id='history-england'/>
## The Shortest History of England

**Summary**: The book gives an insight into the North-South divide in England and how the South-East differs historically from the North and the "Celtics" (Wales, Scotland, Northern Ireland/Ireland). It also gives a fairly clear picture of the political panorama and how the anti-European movements were born and changed over time.

Several Factors contributed to the North-South divide and political landscape:

- **History**: The South-East has historically been richer, has had a very strong elite and has been ruling over the north and trying to rule over the (old) Celtics. Their privileged position comes from the Roman domination, the Norman (French) domination and the wealth obtained from the slave trade (e.g. Bristol). 
- **Two Cultures**: The difference in culture between the South-East and the North of England can also be linked to the Danish and the Vikings who, after conquering most of England, were then defeated by the descendants of Wessex and thus they settled in the "Danelaw" (Northumbria, East-Anglia etc). 
- **Industrial Revolution**: With the first industrial revolution, the north had a chance at ruling over the South-East. A strong new middle / upper class was born not through heredity but through hard work. The North was therefore industrialized but with a different culture. 
- **Education** Universities in the South-East provided a very skilled elite and upper-middle class. (Nonetheless, the UK was the first EU country to develop, over time, a widespread use of Universities all over the country, so it developed a skilled workforce that spanned across classes and made it the intellectual capital of Europe).
- **Parties**: Labour essentially stemmed from Scotland. Tory from the South-East elite. Tory wanted the "old splendor" of the empire, whereas Labour wanted to focus more on the four countries, they were more nationalist in that sense. That's why Tory wanted the UK to join what would become the EU whereas Labour was against it. Eventually, roles reversed in modern times because conservatism became nationalist and the center-left supported internationalization and globalization. 

<div id='ocd'/>
## The Man Who Couldn't Stop

- **What is OCD?**: When intrusive thoughts don't go away (and especially if we try to suppress them, see "white bear effect" Tolstoy) they can turn into obsession and induce anxiety. To reduce this anxiety, people develop compulsions. People say that it feels like living your life on "autopilot" as obsessions often dominate several hours a day.

- **What conditions are related to it?** OCD is a spectrum comprising other conditions that involve intrusive thoughts and compulsive behavior (e.g. hoarders and Tourette). Conditions involving impulsive behavior are often considered in this spectrum too, but impulsive behavior is different as it produces pleasure or reward. These conditions include 

  - Non-paraphillic Sexual Behavior (e.g. sexsomniacs)
  - Trichotillomania (pulling hair), skin-picking, Body Dismorphic Behavior (intrusive thoughts on physical defects)
  - Maladaptive Daydreaming (i.e. compulsive daydreaming)

  OCD can also develop for new parents. This is called Postnatal OCD and it is characterized by parents feeling the urge to kill, hurt or molest their baby. 
  PTSD is also considered related to OCD:

  - Trauma -> fear + disgust at attacker -> PTSD
  - Trauma -> fear + disgust at oneself -> OCD

  Often OCD is confused for Obsessive Compulsive Personality Disorder (OCPD) which is characterized by extreme perfectionism and order, but the difference is that OCPD's thoughts are ego-syntonic, while OCD are ego-dystonic. 

- **Why does it develop?** Since everyone has intrusive thoughts why doesn't everyone develop OCD? It seems to have both a genetic and an environmental cause. Environmentally, early experiences and parenting style leave us with dysfunctional beliefs. For example high parental control & a failure to rewarding independence seems to be correlated with kids developing OCD. Dysfunctional beliefs distort our perception of the world. Three are important for OCD.

  - Inflated sense of responsibility/threat (e.g. explains why some bring pieces of broken glass home: if a stranger injures themselves on the glass, it will be their own fault)
  - Perfectionism & Intolerance of Uncertainty
  - Belief in over-importance of thoughts

  In general, it is often Trauma that triggers OCD. In terms of genes, there is has been speculated that it might be the product of evolution (to help survival of the group, e.g. Waica people drink water from upstream). This would explain why compulsions developed to cope with similar obsession are near-identical across geography and time. There is also some evidence that damages or irregularities in the Basal Ganglia can lead to OCD.

- **Available Treatments**: One often diagnoses OCD using the Yale-Brown scale. In the past relaxation techniques, Freudian psychodynamics and aversion therapy have been tried as treatments but there is no evidence that they work. In terms of pharmacotherapy, Sertraline (neurotransmitter) & other SSRI anti-depressants are used for patients suffering from OCD and about 60% of patients see improvements. Psychotherapy can have great results. CBT (in particular Exposure & Response-Prevention) work by getting the person anxious by stimulating them with the object of their obsession but stop the compulsive behavior. One of the aim is to reveal and identify the dysfunctional belief. 
  If someone in your life suffers from OCD, offering to take responsibility to do something might help, however, it has been shown that non-hostile, non-compliance is the best (rather than compliance or, even worse, hostile non-compliance).

- **Awareness**: OCD often considered minor illness and funny-looking. Awareness is important to make sure perception is shifted and people have equal opportunities in life. 

- **Miscellaneous**: 

  - Questionnaire of Jealousy (University of Pisa) can be used to test obsessional jealousy.
  - Stanley Rachman is one of the biggest expert on OCD.
  - OCD has been reclassified from Anxiety-related to OC-related. It is now also considered a spectrum. This is good because it is easier for researchers to study OCD-related disorders together.
  - People suffering from OCD often trust their memory less. It was shown that in general, repeated checks / perception decreases confidence. 
