---
title: PhD Thesis Code
author: Mauro Camara Escudero
date: '2024-01-29'
slug: code
categories:
  - abc
  - smc
  - mcmc
tags:
  - abc
  - smc
  - mcmc
subtitle: 'Code to reproduce the examples in the thesis.'
summary: ''
authors: []
lastmod: '2024-01-29T14:34:07+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

<iframe width="420" height="315"
src="https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1&mute=1">
</iframe>

Sadly, Chromium does not allow embedded links to be on autoplay unless they are on mute, so yes, technically you have not been Rick-rolled. This webpage is a one-stop-shop for all things code regarding my PhD thesis "Approximate Manifold Sampling". 

1. Quick, easy, simple code to check your understanding.
    - [THUG sampler](https://colab.research.google.com/drive/1x8_sjd5zMat6ECRdX_PaiDREUzbTG1uG?usp=sharing)
2. Reproduce the experiments in the thesis.
3. Off-the-shelf implementation

### Why have I structured the code this way?
I believe there are two reasons researchers check out a paper's accompanying code:

1. They want to check how something is implemented, perhaps they have not understood something in the text.
2. They want to use the code to either reproduce the experiments or to apply it seemlessly into their application.

Something that has frustrated me a lot has been that these two aims have been muddled up together, and I think this is counterproductive. People in the first group want to simply check their understanding, people in the second group don't necessarily need to understand the inner working of the algorithm, they just want a quick-and-easy way to test if the algorithm works in their application. I claim these are two entirely different tasks which are usually solved together. As a result, huge well-crafted Python packages are typically created which can be incredibly hard to read, but very easy to use for simple purposes, but hard to adapt. This is what I believe that a researcher aiming to check their understanding or see how an algorithm is implemented should take less than one minute to find the relevant part of the code.

For instance the [THUG Sampler Colab Notebook](https://colab.research.google.com/drive/1x8_sjd5zMat6ECRdX_PaiDREUzbTG1uG?usp=sharing)'s aim is to maximise readability and minimize time spent looking for the revelant part of the code. For this reason, I have imported most NumPy functions to create less visual clutter, and I have minimised commenting (which was painful, since I love creating helpful docstrings).




